// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseTransition: typeof import('./src/components/transitions/BaseTransition.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    FadeTransition: typeof import('./src/components/transitions/FadeTransition.vue')['default']
    ListLoaded: typeof import('./src/components/ListLoaded.vue')['default']
    ListSkeleton: typeof import('./src/components/ListSkeleton.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    PathEdit: typeof import('./src/components/PathEdit.vue')['default']
    PathNavigator: typeof import('./src/components/PathNavigator.vue')['default']
    SlideXTransition: typeof import('./src/components/transitions/SlideXTransition.vue')['default']
    SlideYTransition: typeof import('./src/components/transitions/SlideYTransition.vue')['default']
  }
}

export { }
