import camelcase from 'camelcase';
import { dirname, parse } from 'path';
import fs from 'fs';
import { Extension, generateImportStatements } from '~/scripts/generateImports';

function updatePluginsIndex(
    path: string,
    category?: string,
    extensions: Extension[] = ['.ts'],
    pascalCase = true,
): void {
    const { result, fileList } = generateImportStatements(path, extensions, pascalCase);

    const categoryName = category || dirname(fileList[0]).split('/').pop();

    const plugins: string[] = [];

    fileList.forEach((filePath) => {
        const { name } = parse(filePath);
        plugins.push(camelcase(name, { pascalCase }));
    });

    const functionName = camelcase(`get-${categoryName}-plugins`);

    const fileExt = extensions[0];
    const content = `// This file was automatically generated by updatePluginsIndex.ts
${result}
function ${functionName}() {
    return [${plugins.join(', ')}];
}

export { ${functionName} };
`;
    const destination = `${path}/index${fileExt}`;

    fs.writeFileSync(destination, content);
    console.log(`[updatePluginsIndex] Successfully update index file: ${destination}`);
}

export { updatePluginsIndex };
