// This file was automatically generated by updatePluginsIndex.ts
import AutoImport from './autoImport';
import Components from './components';
import Inspect from './inspect';
import Layout from './layout';
import Mkcert from './mkcert';
import Page from './page';
import Unocss from './unocss';
import Vue from './vue';
import VueTypeImports from './vueTypeImports';

function getCommonPlugins() {
    return [AutoImport, Components, Inspect, Layout, Mkcert, Page, Unocss, Vue, VueTypeImports];
}

export { getCommonPlugins };
