// This file was automatically generated by updatePluginsIndex.ts
import ManualChunksCompletion from './manualChunksCompletion';
import Visualizer from './visualizer';

function getClientPlugins() {
    return [ManualChunksCompletion, Visualizer];
}

export { getClientPlugins };
